version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - ./gradlew -Pchatbots.env=googlechat build
      - aws lambda update-function-code --function-name exchangeratesbot-googlechat --zip-file fileb://build/libs/exchangesratesbotgooglechat-0.1.jar --publish
      - ./gradlew -Pchatbots.env=telegram build
        - aws lambda update-function-code --function-name exchangeratesbot-telegram --zip-file fileb://build/libs/exchangesratesbottelegram-0.1.jar --publish
  post_build:
    finally:
      - rm -f  /root/.gradle/caches/modules-2/modules-2.lock
      - rm -fr /root/.gradle/caches/*/plugin-resolution/
artifacts:
  files:
    - 'function.zip'
  base-directory: 'build'
cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'