micronaut:
  function:
    name: ForeignExchangeRatesBot
---
telegram:
  bots:
    commands:
      about:
        parse-mode: 'Markdown'
        path: 'classpath:about.md'
      help:
        parse-mode: 'Markdown'
        path: 'classpath:help.md'
exchangerates:
  read-timeout: 30s